spring.application.name=notificacao
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false


spring.rabbitmq.host=localhost
spring.rabbitmq.port=suasenha
spring.rabbitmq.username=seuusuario
spring.rabbitmq.password=suasenha
