spring.application.name=notificacao
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

spring.rabbitmq.listener.simple.retry.max-attempts=5
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=30000




spring.datasource.url=jdbc:postgresql://localhost:5432/notificacao
spring.datasource.username=${DB_USUARIO:postgres}
spring.datasource.password=${DB_SENHA:1212}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USUARIO:admin}
spring.rabbitmq.password=${RABBIT_SENHA:admin}

spring.rabbitmq.listener.simple.retry.max-interval=30000


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

